### ISSUE TITLE
Running Pasture on headless machine

### ISSUE THREAD

**Issue by hieu1999210** [real-stanford/cow#1]
Hi Samir,
Is it possible to run an evaluation on the Pasture benchmark using a headless machine? If so, could you please give more details about how to do it?
Thanks

**Comment by sagadre** [comment]
Yes! It is important that Xorg processes are running on each GPU. If you do `nvidia-smi` you should see a `/usr/lib/xorg/Xorg` process or similar on each GPU. If this is not the case see the README on how to launch these processes. In brief, you will run something like `sudo python scripts/startx.py` from the `cow/` root directory.

Closing the issue for now, but feel free to let me know if you have more questions!
