### ISSUE TITLE
Unable to replicate the results, what's the config used for MP3D?

### ISSUE THREAD

**Issue by sairitwik27** [real-stanford/cow#10]
Hi I am trying to replicate the Habitat MP3D results(SPL=3.7 and SR=7.4) I don't see the objectnav yaml config being used here. I have an A40 so I had to change the torch version to 1.10.2 and CUDA version to 11.3.

This is my objectnav yml file:

 TASK:
  TYPE: ObjectNav-v1
  POSSIBLE_ACTIONS: ["STOP", "MOVE_FORWARD", "TURN_LEFT", "TURN_RIGHT", "LOOK_UP", "LOOK_DOWN"]
  SUCCESS_DISTANCE: 0.1

  SENSORS: ['OBJECTGOAL_SENSOR', 'COMPASS_SENSOR', 'GPS_SENSOR']
  GOAL_SENSOR_UUID: objectgoal

  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SUCCESS', 'SPL', 'SOFT_SPL']

  DISTANCE_TO_GOAL:
    DISTANCE_TO: VIEW_POINTS

  SUCCESS:
    SUCCESS_DISTANCE: 0.1

DATASET:
  TYPE: ObjectNav-v1
  SPLIT: val
  DATA_PATH: "datasets/objectnav/mp3d/v1/{split}/{split}.json.gz"

If there's anything I am missing in my config it'd be great to know

**Comment by sagadre** [comment]
Hi @sairitwik27, checkout the [pasture setup](https://github.com/columbia-ai-robotics/cow#pasture-benchmark-setup) in the readme, specifically these steps:

```
wget https://cow.cs.columbia.edu/downloads/datasets.tar.gz
tar -xvf datasets.tar.gz
```

The config should then be present at: `datasets/habitat/configs/tasks/objectnav_mp3d.yaml`

See [here](https://github.com/columbia-ai-robotics/cow/blob/833f421978c378c1f7b1196ace39e6d226c71090/habitat_mp3d_runner.py#L412) where the config is loaded.

Also see [here](https://github.com/columbia-ai-robotics/cow/tree/main#habitat-mp3d-benchmark-setup) for downloading the necessary MP3D assets and [here](https://github.com/columbia-ai-robotics/cow/tree/main#evaluation-on-habitat-mp3d) for running evals with the repo.

**Comment by sairitwik27** [comment]
Ah shoot don't know how I missed it. Thanks a lot
