### ISSUE TITLE
Questions about config in habitat_mp3d_runner.py

### ISSUE THREAD

**Issue by yh83305** [real-stanford/cow#18]
In habitat_mp3d_runner.py:from 411 to 417:
`mp.set_start_method('spawn', force=True)
    config = habitat.get_config(
    config_paths='datasets/habitat/configs/tasks/objectnav_mp3d.yaml')
    config.defrost()
    config.DATASET.DATA_PATH = 'datasets/habitat/datasets/objectnav/mp3d/v1/val/val.json.gz'
    config.DATASET.SCENES_DIR = 'datasets/habitat/scene_datasets/'
    config.freeze()
`
I couldn't find where these config files are,and when I run :
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib
export HABITAT_BASE_DIR=datasets/habitat
ln -s datasets/habitat data
python habitat_mp3d_runner.py -a src.models.agent_fbe_owl -n 8 --arch B32 --center
`
The result is:
`Traceback (most recent call last):
  File "habitat_mp3d_runner.py", line 19, in <module>
    from src.allenact_experiments.shared.objectnav_habitat_base_config import \
  File "/home/ubuntu/Desktop/cow/src/allenact_experiments/shared/objectnav_habitat_base_config.py", line 31, in <module>
    class ObjectNavHabitatBaseConfig(BaseConfig, ABC):
  File "/home/ubuntu/Desktop/cow/src/allenact_experiments/shared/objectnav_habitat_base_config.py", line 51, in ObjectNavHabitatBaseConfig
    os.path.join(HABITAT_CONFIGS_DIR, "tasks/objectnav_mp3d.yaml")
  File "/home/ubuntu/miniconda3/envs/cow/lib/python3.7/site-packages/allenact_plugins/habitat_plugin/habitat_utils.py", line 245, in get_habitat_config
    f"Could not find config file with given relative path {path}. Tried the following possible absolute"
FileExistsError: Could not find config file with given relative path datasets/habitat/configs/tasks/objectnav_mp3d.yaml. Tried the following possible absolute paths ['/home/ubuntu/Desktop/cow/datasets/habitat/configs/tasks/objectnav_mp3d.yaml', 'datasets/habitat/datasets/habitat/configs/tasks/objectnav_mp3d.yaml', 'datasets/habitat/configs/datasets/habitat/configs/tasks/objectnav_mp3d.yaml'].
`
How to solve it???

**Comment by yh83305** [comment]
I solve it.

**Comment by mengmeng6660** [comment]
how to solve it?
