### ISSUE TITLE
the speed of FBE

### ISSUE THREAD

**Issue by coralkwok** [real-stanford/cow#6]
Hello, I want to ask how is the speed of cow [fbe.update_map](https://github.com/columbia-ai-robotics/cow/blob/main/src/models/agent_fbe.py#L80). I reproduce cow on our simulator, but fbe runs very slowly, it takes about 165-185s to update the map

**Comment by sagadre** [comment]
interesting, are you using this repo or did you try to re-implement from scratch? [this line](https://github.com/columbia-ai-robotics/cow/blob/833f421978c378c1f7b1196ace39e6d226c71090/src/models/agent_fbe.py#LL73C1-L73C1) is very important if you have a machine with many cpus as it prevents cache invalidations.

what happens when you run `htop` while the cow code is running? is cpu utilization high on 1 core or on many cores? what command line are you running?

**Comment by coralkwok** [comment]
yeah, I use this repo, just change the environment-related interface to run
cow on our simulator, I use a machine with 8*3090, 64 cpus, currently our
simulator does not support mutil-progress parallelism (there is bug), so I
only use one card, and want to have a progress, single thread.

This is how I run htop
[image: image.png]
[image: image.png]
[image: image.png]
[image: 6dfb43e1-2f92-4e2c-91ed-04c877b895ab.png]
—
But multi-process seems to have 9 processes, I didn't set this, only -n 1

It seems that the cache is indeed invalid, but I have not changed this line
<https://github.com/columbia-ai-robotics/cow/blob/833f421978c378c1f7b1196ace39e6d226c71090/src/models/agent_fbe.py#LL73C1-L73C1>,
and I am consistent with the original cow on these lines(1
<https://github.com/columbia-ai-robotics/cow/blob/833f421978c378c1f7b1196ace39e6d226c71090/habitat_mp3d_runner.py#L26>
,2
<https://github.com/columbia-ai-robotics/cow/blob/833f421978c378c1f7b1196ace39e6d226c71090/habitat_mp3d_runner.py#L99>
,3
<https://github.com/columbia-ai-robotics/cow/blob/833f421978c378c1f7b1196ace39e6d226c71090/habitat_mp3d_runner.py#LL157C7-L157C7>
,4
<https://github.com/columbia-ai-robotics/cow/blob/833f421978c378c1f7b1196ace39e6d226c71090/habitat_mp3d_runner.py#L411>
)

I run cow code with this command CUDA_VISIBLE_DEVICES=1  python
ue5_runner.py  -a src.models.agent_fbe_patch -n 1 --arch B32 --center
--num_processes 1 --num_processes_per_gpu 0 --num_processes_on_first_gpu 1

Is it because our simulator cannot support multi-processes that pool =
Pool(processes=nprocesses)
<https://github.com/columbia-ai-robotics/cow/blob/833f421978c378c1f7b1196ace39e6d226c71090/habitat_mp3d_runner.py#LL157C7-L157C7>
cannot be used, although nprocesses=1?

Is the cow repo cached on a single cpu? How should I debug it so that the
cache can be restored without multi-process
<https://github.com/columbia-ai-robotics/cow/blob/833f421978c378c1f7b1196ace39e6d226c71090/habitat_mp3d_runner.py#L26>
and not affected by this
<https://github.com/columbia-ai-robotics/cow/blob/833f421978c378c1f7b1196ace39e6d226c71090/src/models/agent_fbe.py#LL73C1-L73C1>
?

thanks a million.

**Comment by coralkwok** [comment]
yeah, I use this repo, just change the environment-related interface to run cow on our simulator, I use a machine with 8*3090, 64 cpus, currently our simulator does not support mutil-progress parallelism (there is bug), so I only use one card, and want to have a progress, single thread.
![image](https://github.com/columbia-ai-robotics/cow/assets/100067283/8a3296ee-bf9b-4712-9d80-3c7954802376)
![image](https://github.com/columbia-ai-robotics/cow/assets/100067283/297af92d-4fd9-409e-943d-11e530065da5)
![image](https://github.com/columbia-ai-robotics/cow/assets/100067283/011d85ef-5d7b-4b05-9a92-9da1d6dd4314)
![image](https://github.com/columbia-ai-robotics/cow/assets/100067283/f22a6782-4e75-4dc4-a16b-0ba1b878d59f)
But `multi-process` seems to have 9 processes, I didn't set this, only -n 1

It seems that the cache is indeed invalid, but I have not changed this [line](https://github.com/columbia-ai-robotics/cow/blob/833f421978c378c1f7b1196ace39e6d226c71090/src/models/agent_fbe.py#LL73C1-L73C1) and I am consistent with the original cow on these lines [1](https://github.com/columbia-ai-robotics/cow/blob/833f421978c378c1f7b1196ace39e6d226c71090/habitat_mp3d_runner.py#L26),[2](https://github.com/columbia-ai-robotics/cow/blob/833f421978c378c1f7b1196ace39e6d226c71090/habitat_mp3d_runner.py#L99),[3](https://github.com/columbia-ai-robotics/cow/blob/833f421978c378c1f7b1196ace39e6d226c71090/habitat_mp3d_runner.py#LL157C7-L157C7),[4](https://github.com/columbia-ai-robotics/cow/blob/833f421978c378c1f7b1196ace39e6d226c71090/habitat_mp3d_runner.py#L411))
I run cow code with this command `CUDA_VISIBLE_DEVICES=1  python ue5_runner.py  -a src.models.agent_fbe_patch -n 1 --arch B32 --center  --num_processes_per_gpu 0 --num_processes_on_first_gpu 1`

Is it because our simulator cannot support multi-processes that [pool = Pool(processes=nprocesses)](https://github.com/columbia-ai-robotics/cow/blob/833f421978c378c1f7b1196ace39e6d226c71090/habitat_mp3d_runner.py#LL157C7-L157C7) cannot be used, although nprocesses=1?

Is the cow repo cached on a single cpu? How should I debug it so that the cache can be restored without [multi-process](https://github.com/columbia-ai-robotics/cow/blob/833f421978c378c1f7b1196ace39e6d226c71090/habitat_mp3d_runner.py#L26) and not affected by [this](https://github.com/columbia-ai-robotics/cow/blob/833f421978c378c1f7b1196ace39e6d226c71090/src/models/agent_fbe.py#LL73C1-L73C1)?

thanks a million.

**Comment by sagadre** [comment]
Sorry I am not familiar with the specifics of your simulator making it a bit difficult to help here. One thing you might try is to call the [worker function](https://github.com/columbia-ai-robotics/cow/blob/833f421978c378c1f7b1196ace39e6d226c71090/habitat_mp3d_runner.py#L160) directly without the multiprocessing pool.

**Comment by coralkwok** [comment]
Thank you, I also tried directly call the [worker function](https://github.com/columbia-ai-robotics/cow/blob/833f421978c378c1f7b1196ace39e6d226c71090/habitat_mp3d_runner.py#L160), it didn't solve it. Now I'm trying other methods, and will close this issue later, I want to ask that change the size of the image input(eg.[3, 480, 640]), then in [clip_grad](https://github.com/columbia-ai-robotics/cow/blob/main/src/models/localization/clip_grad.py#L74), it will [not match](https://github.com/columbia-ai-robotics/cow/blob/main/src/clip/model.py#L224) because of the loaded weight, so I can only use `nnf.interpolate `to make it become (224,224), the same in [clip_patch](https://github.com/columbia-ai-robotics/cow/blob/main/src/models/localization/clip_patch.py#L65), is there any other way?

**Comment by sagadre** [comment]
Got it! Also a good check to see if you can run the code on a single CPU core and make sure that the CPU utilization is very high.

CLIP unfortunately only accepts 224x224 images. For 480x640 input one could potentially:
1. resize to 224x224 and not maintain aspect ratio
2. resize with smaller dimension set to 224 and take center crop
3. resize the larger dimension to 224 and pad the image for the smaller dimension

**Comment by coralkwok** [comment]
Alright. I get it, thank you! But I resize the calculated tensor back to (480,640) after resizing this way, will it affect the detection result?  because I need a result of (480, 640)as input for other calculations

**Comment by sagadre** [comment]
Depending on what you are doing, it is possible that changing the resolution will change the results. For your new simulator, I would recommend setting up a evaluation set and seeing to what degree these choices affect downstream performance. Good luck!

**Comment by coralkwok** [comment]
okey. thank you!
