### ISSUE TITLE
Top-down Visualization

### ISSUE THREAD

**Issue by JasonHysy** [real-stanford/cow#8]
Hello Samir,
Thanks for this amazing work!
How did you guys generate the top-down view? Was it generated manually by retracing the trajectory or there is a built-in package to achieve this visualization? 
Also same question for the object relevance mapping visualization, if that's okay.
Sorry if these questions are possibly basic, I've scrolled through ai2thor's documentation and they didn't say anything about top-down visualization, only the robot's camera.
Thank you so much in advance!

**Comment by sagadre** [comment]
No worries! I used the code linked here: https://github.com/allenai/cordial-sync/issues/5

**Comment by JasonHysy** [comment]
I will look into the code. Thank you so much Samir!

**Comment by JasonHysy** [comment]
Hello Samir,

Firstly thank you again for the reply! And I've found that you have implemented the visualization_utils.py for drawing top_down trajectory. Thank you again for this!
Also just wandering, is there any implemented util functions to draw out the frontier map as shown in the paper? 
![image](https://github.com/columbia-ai-robotics/cow/assets/103576156/5c9a7857-5357-47a3-ac5e-d70663883ffb)
Or we need to look into the frontier_based_exploration.py and implement our own visualization function?

**Comment by sagadre** [comment]
Hi Jason, unfortunately I don't have a clean function for this. You can call [this function](https://github.com/columbia-ai-robotics/cow/blob/833f421978c378c1f7b1196ace39e6d226c71090/src/models/exploration/frontier_based_exploration.py#L197) on a `FrontierBasedExploration` object (e.g., in these [lines](https://github.com/columbia-ai-robotics/cow/blob/833f421978c378c1f7b1196ace39e6d226c71090/robothor_challenge.py#L372)). From there you can use Blender or even meshlab to render the ply. For this figure I used meshlab

**Comment by JasonHysy** [comment]
Thanks Samir! 
I did try out this function as well, but for the ply file I see, I wasn't able to see frontiers being marked like figure(a), only the object relevance map similar to figure (b). Are the frontiers marked manually or I should look more into the frontier information in the frontier_based_exploration.py?

**Comment by sagadre** [comment]
You can set colors [here](https://github.com/columbia-ai-robotics/cow/blob/833f421978c378c1f7b1196ace39e6d226c71090/src/models/exploration/frontier_based_exploration.py#L68). Currently, the frontier is set to white, probably because I made figure (b) after I made figure (a) 🙂

**Comment by JasonHysy** [comment]
Oh I see that's why! Thank you so much again for all the help!
